# Generated by Django 4.2.4 on 2023-11-18 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_user_date_of_birth"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="friendrequest",
            name="is_accepted",
        ),
        migrations.AlterField(
            model_name="friendrequest",
            name="from_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_request",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="friendrequest",
            name="message",
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name="friendrequest",
            name="to_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_request",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
