# Generated by Django 4.2.4 on 2023-11-25 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="record",
            name="game_level",
        ),
        migrations.AddField(
            model_name="record",
            name="attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="record",
            name="game",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="games.game",
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="level",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="game",
            name="category",
            field=models.CharField(
                choices=[("Maths", "maths"), ("English", "english"), ("Game", "game")],
                max_length=60,
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="end_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="GameLevel",
        ),
    ]
