# Generated by Django 4.2.4 on 2023-11-25 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_remove_record_game_level_record_attempts_record_game_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="games.game",
            ),
        ),
    ]
