# Generated by Django 4.2.4 on 2023-11-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0003_alter_record_game"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="category",
            field=models.CharField(
                choices=[("maths", "Maths"), ("english", "English"), ("game", "Game")],
                max_length=60,
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="end_timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="start_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
