# Generated by Django 4.2.4 on 2023-11-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0004_alter_game_category_alter_record_end_timestamp_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="record",
            name="start_timestamp",
        ),
    ]
