# Generated by Django 4.2.4 on 2023-11-26 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0005_remove_record_start_timestamp_record_game_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="game_time",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
